### ISSUE TITLE
The Game Crashed

### ISSUE THREAD

**Issue by Pistachioman1** [Disketaa/Minecraft-Enhanced#5]
The game crashes every time I launch the game

**Comment by Disketaa** [comment]
Hi! Can you send me your crash-log?

**Comment by crowbeary** [comment]
I'm having the same issue. Every time I click play in the official Minecraft launcher, I get a crash report as soon as the launcher disappears. (sorry if this isn't the right way to submit this, I have never used this site before)

Uncaught exception in thread "main"
java.lang.NoSuchMethodError: 'void net.fabricmc.loader.impl.util.log.LogCategory.<init>(java.lang.String[])'
	at io.gitlab.jfronny.libjf.unsafe.JfLanguageAdapter.<clinit>(JfLanguageAdapter.java:18)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:400)
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:310)
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:110)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Disketaa** [comment]
Greetings! Here's a few questions:

1. Are you using CurseForge version of this modpack?
2. Are you using the last release version of this modpack?
3. Crash happens everytime on launching or just for once then game launch normally?

**Comment by crowbeary** [comment]
1. Yes, I open the CurseForge app and then it opens the launcher with the modpack profile I selected.
2. I originally installed 2.1 which was the current release at the time but today there is a 2.2 version which I can't install. It fails every time I try, I even fully deleted the pack's profile and tried to reinstall as 2.2 instead of just updating the version and it just cancels the installation after trying to validate the manifest files (? something like that) every time.
3. It's crashed every time I tried, the modpack has never successfully launched for me.

**Comment by crowbeary** [comment]
Update: not really sure what changed but I was able to install 2.2. I'm still getting the same crash reports. The one I sent before is a separate window that pops up first and once I hit exit, the launcher opens back up with the attached screen.
![crash message](https://user-images.githubusercontent.com/105082195/167271322-e6ac9fb5-25cc-43c0-908d-76f2fd024692.PNG)

**Comment by Disketaa** [comment]
Okay, I'm figuring out

**Comment by Disketaa** [comment]
Check out 2.3.
Should be fixed.

**Comment by Disketaa** [comment]
CurseForge client is down for today. So no 2.3 in it yet
